document.writeln("<style type=\'text/css\'>");
document.writeln("       .nav{");
document.writeln("           padding:0px;");
document.writeln("           margin:0px;");
document.writeln("           list-style-type:none;");
document.writeln("           overflow: hidden;");
document.writeln("            background-color:#3D59AB;;");
document.writeln("       }");
document.writeln("        .nav li {");
document.writeln("            float: left;");
document.writeln("            margin: 0 40px;");
document.writeln("            padding-top:21px;");
document.writeln("        }");
document.writeln("        .nav a{");
document.writeln("            height: 33px;");
document.writeln("            padding-left: 10px;");
document.writeln("            color: #fff;");
document.writeln("            display: block;");
document.writeln("            line-height: 33px;");
document.writeln("            font-weight: 700;");
document.writeln("            font-size:18px;");
document.writeln("            text-decoration:none;");
document.writeln("        }");
document.writeln("    </style>");
document.writeln("<body>");
document.writeln("<div class=\'a\'><img src=\'img/d3.png\' /></div>");
document.writeln("  <div class=\'box_topbar\'>");
document.writeln("   <div class=\'nav\'>");
document.writeln("        <li><a href=\'index.html\'>首页</a></li>");
document.writeln("        <li><a href=\'华水风采.html\'>华水风采</a></li>");
document.writeln("        <li><a href=\'华水校友.html\'>华水校友</a></li>");
document.writeln("        <li><a href=\'http://www.ncwu.edu.cn/\'>学校官网</a></li>");
document.writeln("     </ul>");
document.writeln("  </div>");
document.writeln("</div>");
document.writeln("</body></html>");